FROM node:12-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy packages to the docker image
COPY package*.json ./

# Installing dependencies
RUN npm i
# RUN npm ci --only=production

# Copy the rest of the content
COPY . .

RUN npm run build

# Opening port 3000
EXPOSE 3000:3000

VOLUME [ "./:/src/app"]

CMD npm start