version: "3.8"

services:
  next:
    container_name: next
    image: node:12-alpine
    working_dir: /app
    #environment:
    #- NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # Live reload for modules
      - /app/node_modules
      # Live reload for next
      - /app/.next
    command: sh -c "npm install && npm run dev"
    depends_on:
      - strapi

  strapi:
    build: ./api
    container_name: strapi
    image: strapi/base
    working_dir: /srv/app
    ports:
      - "1337:1337"
    volumes:
      - ./api:/srv/app
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    command: sh -c "npm install && npm run develop"

  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
