FROM strapi/base

# Create app directory
WORKDIR /usr/srv/app

# Copy packages to the docker image
COPY package.json ./

# Installing dependencies
RUN npm ci --only=production

# Copy the rest of the content
COPY . ./

ENV NODE_ENV production

RUN npm run build

# Opening port 1337
EXPOSE 1337:1337

# Mounting volume to current directory
VOLUME [ "./:/usr/srv/app" ]

CMD npm run start