name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: false
          
  community-platform:

    name: Build & push community-platform
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile.production --tag astroplant/astroplant-community-platform:latest
        docker push astroplant/astroplant-community-platform:latest

  community-api:

    name: Build & push community-api
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push the Docker image
      run: |
        docker build . --file api/Dockerfile.production --tag astroplant/astroplant-community-api:latest
        docker push astroplant/astroplant-community-api:latest
