name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: false
          
      - name: Build and push the platform image
        run: |
          docker build . --file Dockerfile.production --tag astroplant/astroplant-community-platform:latest
          docker push astroplant/astroplant-community-platform:latest
          
      - name: Build and push the community api image
        run: |
          docker build ./api --file api/Dockerfile.production --tag astroplant/astroplant-community-api:latest
          docker push astroplant/astroplant-community-api:latest
